name: Say Hello
run-name: example of run name

on: [push]

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - run : |
          echo "hey there"
          echo "what here"
    
      - run : echo "weeeee" 
  
