name: Say Hello

on:
  workflow_dispatch:
    inputs:
      name:
         description: "name to grate"
         default: "gust"
         required: false

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - run : |
          echo "hey ${{ inputs.name }} "
          echo "what here"
    
      - run : echo "weeeee" 
  
